controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

pwm_pid_controller:
  ros__parameters:
    type: pid_controller/PidController

    dof_names:
      - front_left_wheel_joint
    
    command_interface: effort

    reference_and_state_interfaces: ["velocity"]

    gains:
      front_left_wheel_joint: {p: 0.0001, i: 10.0, d: 0.0001, i_clamp_max: 3.5, i_clamp_min: -3.5}