controller_manager:
  ros__parameters:
    update_rate: 25  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# first layer controller
pwm_pid_controller:
  ros__parameters:
    type: pwm_pid_controller/PwmPidController

    dof_names:
      - front_left_wheel_joint
      - rear_left_wheel_joint
      - front_right_wheel_joint
      - rear_right_wheel_joint
    
    command_interface: effort

    reference_and_state_interfaces: ["velocity"]

    gains:
      front_left_wheel_joint:  {p: 10.0, i: 300.0, d: 0.1, i_clamp_max: 3500.0, i_clamp_min: -3500.0, out_dead_zone_high: 270.0, out_dead_zone_low: -270.0} # gains work for average window size = 1 and 6
      rear_left_wheel_joint:   {p: 10.0, i: 300.0, d: 0.1, i_clamp_max: 3500.0, i_clamp_min: -3500.0, out_dead_zone_high: 270.0, out_dead_zone_low: -270.0} # less of deviation of effort with size 6
      front_right_wheel_joint: {p: 10.0, i: 300.0, d: 0.1, i_clamp_max: 3500.0, i_clamp_min: -3500.0, out_dead_zone_high: 270.0, out_dead_zone_low: -270.0}
      rear_right_wheel_joint:  {p: 10.0, i: 300.0, d: 0.1, i_clamp_max: 3500.0, i_clamp_min: -3500.0, out_dead_zone_high: 270.0, out_dead_zone_low: -270.0}

# second layer controller
diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController

    left_wheel_names: ["pwm_pid_controller/front_left_wheel_joint", "pwm_pid_controller/rear_left_wheel_joint"]
    right_wheel_names: ["pwm_pid_controller/front_right_wheel_joint", "pwm_pid_controller/rear_right_wheel_joint"]

    wheel_separation: 0.10
    wheel_radius: 0.0325

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # publish_rate: 50.0 # for odometry
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    position_feedback: false
    # open_loop: true
    # enable_odom_tf: true

    cmd_vel_timeout: 0.5 # seconds
    # publish_limited_velocity: true
    # velocity_rolling_window_size: 10 # used in odemetry

    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 0.7
    linear.x.max_deceleration: -0.7
    linear.x.max_acceleration_reverse: -0.7
    linear.x.max_deceleration_reverse: 0.7
    linear.x.max_jerk: .NAN
    linear.x.min_jerk: .NAN

    angular.z.max_velocity: 10.0
    angular.z.min_velocity: -10.0
    angular.z.max_acceleration: 10.0
    angular.z.max_deceleration: -10.0
    angular.z.max_acceleration_reverse: -10.0
    angular.z.max_deceleration_reverse: 10.0
    angular.z.max_jerk: .NAN
    angular.z.min_jerk: .NAN                          