sonar_front:
  ros__parameters:
    trigger_gpio: 22
    echo_gpio: 23
    measurement_time: 40
    time_between_measurements: 30
    field_of_view: 15.0
    min_range: 0.02
    max_range: 3.00
    
sonar_left:
  ros__parameters:
    trigger_gpio: 27
    echo_gpio: 18
    measurement_time: 40
    time_between_measurements: 30
    field_of_view: 15.0
    min_range: 0.02
    max_range: 3.00

sonar_right:
  ros__parameters:
    trigger_gpio: 25
    echo_gpio: 24
    measurement_time: 40
    time_between_measurements: 30
    field_of_view: 15.0
    min_range: 0.02
    max_range: 3.00