sonar_front:
  ros__parameters:
    trigger_gpio: 22
    echo_gpio: 23
    measurement_time: 30
    field_of_view: 15.0
    min_range: 0.02
    max_range: 3.00
    
# sonar_left:
#   ros__parameters:
#     trigger_gpio:
#     echo_gpio:
#     timeout:

# sonar_right:
#   ros__parameters:
#     trigger_gpio:
#     echo_gpio:
#     timeout: