<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="morve_description_urdf" params="prefix">
    
    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="base_mass" value="0.3" /> <!-- arbitrary value for base mass -->
    <xacro:property name="base_width" value="0.16" />
    <xacro:property name="base_length" value="0.2" />
    <xacro:property name="base_height" value="0.005" />
    <xacro:property name="wheel_mass" value="0.3" /> <!-- arbitrary value for wheel mass -->
    <xacro:property name="wheel_length" value="0.025" />
    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="track_width" value="0.2" />
    <xacro:property name="wheel_base" value="0.12" />
    <xacro:property name="track_width_half" value="${track_width/2}"/>
    <xacro:property name="wheel_base_half" value="${wheel_base/2}" />
    <xacro:property name="z_offset" value="${base_height/2}" /> <!-- Space btw top of beam and the each joint -->
    
    
    <!-- Base link -->
    <link name="${prefix}base_link">
        <visual>
             <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
             <geometry>
                <box size="${base_width} ${base_length} ${base_height}"/>
             </geometry>
             <material name="white"/>        
        </visual>
    </link>
    
    <!-- Front left wheel joint and link (part) -->
    <joint name="${prefix}front_left_wheel_joint" type="continuous">
        <parent link="${prefix}base_link"/>
        <child link="${prefix}front_left_wheel"/>
        <axis xyz="0 0 1"/>
        <origin xyz="${track_width_half} ${-wheel_base_half} ${z_offset}" rpy="0 ${PI/2} 0"/>
    </joint>
    
    <link name="${prefix}front_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="green"/>    
        </visual>
    </link>

    <!-- Test of inserting mesh of sonar holder to urdf -->
    <joint name="${prefix}front_sonar_holder_joint" type="fixed">
        <parent link="${prefix}base_link"/>
        <child link="${prefix}front_sonar_holder"/>
        <origin xyz="0.0 ${-base_length/2} ${z_offset}" rpy="0.0 0.0 0.0"/>
    </joint>
    
    <link name="${prefix}front_sonar_holder">
        <visual>
            <origin xyz="-0.025 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://morve_description/description/meshes/HC_SR04_2021_holder.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

    </xacro:macro>
    
</robot>